/**
 * Snapshot the DB-backed half of the Ask Coach corpus into a test fixture.
 *
 * Retrieval is fitted against the REAL content — thresholds tuned on toy passages
 * would be fitted to nothing. But the unit tests must not hit the network, and
 * two of the four sources (road signs, questions) live in Postgres. So: snapshot
 * them, commit the snapshot, and let the tests build a real corpus offline.
 *
 * The other two sources (road rules, vehicle controls) are TypeScript files the
 * tests import directly — no snapshot needed, and no chance of them going stale.
 *
 * This WILL go stale as content is approved. That is tolerable for a threshold
 * fixture and intolerable for anything else, so nothing but the tests may read
 * it. Re-run after a content push:
 *
 *   node --env-file=.env.local scripts/coach/snapshot-corpus.mjs
 */
import { writeFileSync } from "node:fs";

const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error("Need NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY (use --env-file=.env.local)");
  process.exit(1);
}

const headers = { apikey: key, authorization: `Bearer ${key}` };

/** PostgREST caps a page at 1000 rows; page until short. */
async function all(path) {
  const out = [];
  for (let from = 0; ; from += 1000) {
    const res = await fetch(`${url}/rest/v1/${path}`, {
      headers: { ...headers, range: `${from}-${from + 999}` },
    });
    if (!res.ok) throw new Error(`${res.status} ${await res.text()}`);
    const page = await res.json();
    out.push(...page);
    if (page.length < 1000) return out;
  }
}

// The served set — both gates approved AND sa_relevant. Same filter as
// getApprovedSigns; a snapshot taken through a looser filter would let the coach
// ground on a sign no learner can see.
const signs = await all(
  "road_signs?select=code,name,category,content&review_status=eq.approved&asset_status=eq.approved&sa_relevant=is.true&order=code",
);

const questions = await all(
  "questions?select=id,topic,prompt,options,answer,explanation,objective_code&review_status=eq.approved&order=id",
);

const snapshot = {
  takenAt: new Date().toISOString(),
  source: "lxefjksaxmiawrnnewmj (production — the only database)",
  note: "Generated by scripts/coach/snapshot-corpus.mjs. Test fixture only; never read at runtime.",
  counts: { signs: signs.length, questions: questions.length },
  signs,
  questions,
};

const out = new URL("../../src/lib/__fixtures__/coach-corpus-snapshot.json", import.meta.url);
writeFileSync(out, JSON.stringify(snapshot, null, 1));
console.log(`signs: ${signs.length}  questions: ${questions.length}  ->  ${out.pathname}`);
